### ISSUE TITLE
Register compatibility with inkscape 1.3

### ISSUE THREAD

**Issue by gersonjferreira** [burghoff/Scientific-Inkscape#20]
The github readme says that the extension is compatible with inkscape 1.3, but the inkscape webpage still shows only versions compatible with version 1.2. Please update the inkscape version on their webpage so we can use the automatic install method.

**Comment by burghoff** [comment]
Yes, it should be working.

Post the error message and attach an SVG.

**Comment by gersonjferreira** [comment]
I've tried to change the size and run "Scale Plots > Correction Mode > Maintain size of plot area".

I'm using Manjaro Linux with Gnome, all updated.

Inkscape: 1.3 (0e150ed6c4, 2023-07-21) -- see ldd output for libs versions below.

Here's the figure:

![BHZ_cond](https://github.com/burghoff/Scientific-Inkscape/assets/5455489/c48b1132-d9e9-4c3f-b9be-e1e9e5d631ed)

The error message:

```bash
Traceback (most recent call last):
  File "/home/gerson/.config/inkscape/extensions/scientific_inkscape/scale_plots.py", line 655, in <module>
    dh.Run_SI_Extension(ScalePlots(),"Scale plots")
  File "/home/gerson/.config/inkscape/extensions/scientific_inkscape/dhelpers.py", line 2134, in Run_SI_Extension
    effext.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 250, in run
    self.save_raw(self.effect())
                  ^^^^^^^^^^^^^
  File "/home/gerson/.config/inkscape/extensions/scientific_inkscape/scale_plots.py", line 283, in effect
    fbbs = dh.BB2(self,dh.unique([d for el in sel for d in dh.descendants2(el)]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gerson/.config/inkscape/extensions/scientific_inkscape/dhelpers.py", line 1325, in BB2
    mbbox = d.cbbox;
            ^^^^^^^
  File "/usr/share/inkscape/extensions/inkex/elements/_base.py", line 147, in __getattr__
    raise AttributeError(f"Can't find attribute {self.typename}.{name}")
AttributeError: Can't find attribute Group.cbbox. Did you mean: '_cbbox'?
```

And the ldd output:

```bash
ldd /usr/bin/inkscape                                                                                                                                  INT ✘ 
	linux-vdso.so.1 (0x00007ffeb5397000)
	libinkscape_base.so.1.3.0.0 => /usr/bin/../lib/inkscape/libinkscape_base.so.1.3.0.0 (0x00007f5ee1e00000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f5ee1cb5000)
	libgiomm-2.4.so.1 => /usr/lib/libgiomm-2.4.so.1 (0x00007f5ee1adf000)
	libglibmm-2.4.so.1 => /usr/lib/libglibmm-2.4.so.1 (0x00007f5ee1a56000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f5ee1600000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f5ee1a31000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f5ee1200000)
	libboost_filesystem.so.1.81.0 => /usr/bin/../lib/inkscape/../libboost_filesystem.so.1.81.0 (0x00007f5ee1a0e000)
	libpangocairo-1.0.so.0 => /usr/bin/../lib/inkscape/../libpangocairo-1.0.so.0 (0x00007f5ee380f000)
	libcairo.so.2 => /usr/bin/../lib/inkscape/../libcairo.so.2 (0x00007f5ee18dc000)
	libpangoft2-1.0.so.0 => /usr/bin/../lib/inkscape/../libpangoft2-1.0.so.0 (0x00007f5ee18c4000)
	libpango-1.0.so.0 => /usr/bin/../lib/inkscape/../libpango-1.0.so.0 (0x00007f5ee1597000)
	libharfbuzz.so.0 => /usr/bin/../lib/inkscape/../libharfbuzz.so.0 (0x00007f5ee148c000)
	libfontconfig.so.1 => /usr/bin/../lib/inkscape/../libfontconfig.so.1 (0x00007f5ee11b1000)
	libfreetype.so.6 => /usr/bin/../lib/inkscape/../libfreetype.so.6 (0x00007f5ee10e3000)
	libgsl.so.27 => /usr/bin/../lib/inkscape/../libgsl.so.27 (0x00007f5ee0e00000)
	libsoup-2.4.so.1 => /usr/bin/../lib/inkscape/../libsoup-2.4.so.1 (0x00007f5ee0d5f000)
	libgmodule-2.0.so.0 => /usr/bin/../lib/inkscape/../libgmodule-2.0.so.0 (0x00007f5ee18bb000)
	libgio-2.0.so.0 => /usr/bin/../lib/inkscape/../libgio-2.0.so.0 (0x00007f5ee0b89000)
	libgobject-2.0.so.0 => /usr/bin/../lib/inkscape/../libgobject-2.0.so.0 (0x00007f5ee0b27000)
	libgc.so.1 => /usr/bin/../lib/inkscape/../libgc.so.1 (0x00007f5ee0abb000)
	liblcms2.so.2 => /usr/bin/../lib/inkscape/../liblcms2.so.2 (0x00007f5ee0a55000)
	libpoppler.so.130 => /usr/bin/../lib/inkscape/../libpoppler.so.130 (0x00007f5ee0600000)
	libpoppler-glib.so.8 => /usr/bin/../lib/inkscape/../libpoppler-glib.so.8 (0x00007f5ee09dd000)
	libwpg-0.3.so.3 => /usr/bin/../lib/inkscape/../libwpg-0.3.so.3 (0x00007f5ee1899000)
	librevenge-0.0.so.0 => /usr/bin/../lib/inkscape/../librevenge-0.0.so.0 (0x00007f5ee145f000)
	librevenge-stream-0.0.so.0 => /usr/bin/../lib/inkscape/../librevenge-stream-0.0.so.0 (0x00007f5ee187b000)
	libvisio-0.1.so.1 => /usr/bin/../lib/inkscape/../libvisio-0.1.so.1 (0x00007f5ee055d000)
	libcdr-0.1.so.1 => /usr/bin/../lib/inkscape/../libcdr-0.1.so.1 (0x00007f5ee04b3000)
	libjpeg.so.8 => /usr/bin/../lib/inkscape/../libjpeg.so.8 (0x00007f5ee0407000)
	libpng16.so.16 => /usr/bin/../lib/inkscape/../libpng16.so.16 (0x00007f5ee03cd000)
	libpotrace.so.0 => /usr/bin/../lib/inkscape/../libpotrace.so.0 (0x00007f5ee1453000)
	libgtkmm-3.0.so.1 => /usr/bin/../lib/inkscape/../libgtkmm-3.0.so.1 (0x00007f5edfe00000)
	libatkmm-1.6.so.1 => /usr/bin/../lib/inkscape/../libatkmm-1.6.so.1 (0x00007f5ee037a000)
	libgdkmm-3.0.so.1 => /usr/bin/../lib/inkscape/../libgdkmm-3.0.so.1 (0x00007f5ee0323000)
	libpangomm-1.4.so.1 => /usr/bin/../lib/inkscape/../libpangomm-1.4.so.1 (0x00007f5ee02f2000)
	libcairomm-1.0.so.1 => /usr/bin/../lib/inkscape/../libcairomm-1.0.so.1 (0x00007f5ee10ba000)
	libsigc-2.0.so.0 => /usr/bin/../lib/inkscape/../libsigc-2.0.so.0 (0x00007f5ee02ea000)
	libgtk-3.so.0 => /usr/bin/../lib/inkscape/../libgtk-3.so.0 (0x00007f5edf600000)
	libgdk-3.so.0 => /usr/bin/../lib/inkscape/../libgdk-3.so.0 (0x00007f5edf507000)
	libz.so.1 => /usr/bin/../lib/inkscape/../libz.so.1 (0x00007f5ee02d0000)
	libgdk_pixbuf-2.0.so.0 => /usr/bin/../lib/inkscape/../libgdk_pixbuf-2.0.so.0 (0x00007f5ee028a000)
	libcairo-gobject.so.2 => /usr/bin/../lib/inkscape/../libcairo-gobject.so.2 (0x00007f5ee027f000)
	libgspell-1.so.2 => /usr/bin/../lib/inkscape/../libgspell-1.so.2 (0x00007f5edfde0000)
	libgtksourceview-4.so.0 => /usr/bin/../lib/inkscape/../libgtksourceview-4.so.0 (0x00007f5edf470000)
	libxslt.so.1 => /usr/bin/../lib/inkscape/../libxslt.so.1 (0x00007f5edf42f000)
	libxml2.so.2 => /usr/bin/../lib/inkscape/../libxml2.so.2 (0x00007f5edf2c9000)
	libreadline.so.8 => /usr/bin/../lib/inkscape/../libreadline.so.8 (0x00007f5edf272000)
	libGraphicsMagick++.so.12 => /usr/bin/../lib/inkscape/../libGraphicsMagick++.so.12 (0x00007f5edf1fa000)
	libepoxy.so.0 => /usr/bin/../lib/inkscape/../libepoxy.so.0 (0x00007f5edf0c9000)
	libX11.so.6 => /usr/bin/../lib/inkscape/../libX11.so.6 (0x00007f5edef86000)
	libm.so.6 => /usr/bin/../lib/inkscape/../libm.so.6 (0x00007f5edee99000)
	lib2geom.so.1.3.0 => /usr/bin/../lib/inkscape/../lib2geom.so.1.3.0 (0x00007f5ededb0000)
	libgomp.so.1 => /usr/bin/../lib/inkscape/../libgomp.so.1 (0x00007f5eded5f000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f5ee385a000)
	libpcre2-8.so.0 => /usr/lib/libpcre2-8.so.0 (0x00007f5edecc4000)
	libboost_atomic.so.1.81.0 => /usr/lib/libboost_atomic.so.1.81.0 (0x00007f5ee0275000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f5edecaf000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f5ee0268000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f5edec84000)
	libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x00007f5edec75000)
	libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x00007f5edfddb000)
	libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x00007f5edebc8000)
	libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x00007f5edeba8000)
	libthai.so.0 => /usr/lib/libthai.so.0 (0x00007f5edeb9d000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f5edeb7a000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f5edeb4f000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f5edeb3c000)
	libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x00007f5edeb2e000)
	libcblas.so.3 => /usr/lib/libcblas.so.3 (0x00007f5edeb10000)
	libsqlite3.so.0 => /usr/lib/libsqlite3.so.0 (0x00007f5ede9b7000)
	libpsl.so.5 => /usr/lib/libpsl.so.5 (0x00007f5ede9a3000)
	libgssapi_krb5.so.2 => /usr/lib/libgssapi_krb5.so.2 (0x00007f5ede94f000)
	libmount.so.1 => /usr/lib/libmount.so.1 (0x00007f5ede8fe000)
	libffi.so.8 => /usr/lib/libffi.so.8 (0x00007f5ede8f3000)
	libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007f5ede843000)
	libgpgmepp.so.6 => /usr/lib/libgpgmepp.so.6 (0x00007f5ede7e0000)
	libopenjp2.so.7 => /usr/lib/libopenjp2.so.7 (0x00007f5ede774000)
	libtiff.so.6 => /usr/lib/libtiff.so.6 (0x00007f5ede6dd000)
	libsmime3.so => /usr/lib/libsmime3.so (0x00007f5ede6b5000)
	libnss3.so => /usr/lib/libnss3.so (0x00007f5ede57b000)
	libplc4.so => /usr/lib/libplc4.so (0x00007f5ede574000)
	libnspr4.so => /usr/lib/libnspr4.so (0x00007f5ede533000)
	libwpd-0.10.so.10 => /usr/lib/libwpd-0.10.so.10 (0x00007f5ede493000)
	libicuuc.so.73 => /usr/lib/libicuuc.so.73 (0x00007f5ede200000)
	libicudata.so.73 => /usr/lib/libicudata.so.73 (0x00007f5edc200000)
	libicui18n.so.73 => /usr/lib/libicui18n.so.73 (0x00007f5edbe00000)
	libatk-1.0.so.0 => /usr/lib/libatk-1.0.so.0 (0x00007f5ede469000)
	libXi.so.6 => /usr/lib/libXi.so.6 (0x00007f5ede455000)
	libatk-bridge-2.0.so.0 => /usr/lib/libatk-bridge-2.0.so.0 (0x00007f5ede41a000)
	libcloudproviders.so.0 => /usr/lib/libcloudproviders.so.0 (0x00007f5ede1e9000)
	libtracker-sparql-3.0.so.0 => /usr/lib/libtracker-sparql-3.0.so.0 (0x00007f5ede10e000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007f5ede410000)
	libxkbcommon.so.0 => /usr/lib/libxkbcommon.so.0 (0x00007f5ede0c7000)
	libwayland-client.so.0 => /usr/lib/libwayland-client.so.0 (0x00007f5ede0b5000)
	libwayland-cursor.so.0 => /usr/lib/libwayland-cursor.so.0 (0x00007f5ede0ab000)
	libwayland-egl.so.1 => /usr/lib/libwayland-egl.so.1 (0x00007f5ede409000)
	libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x00007f5ede09f000)
	libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x00007f5ede09a000)
	libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0x00007f5ede095000)
	libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x00007f5edc1f3000)
	libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x00007f5ede08e000)
	libenchant-2.so.2 => /usr/lib/libenchant-2.so.2 (0x00007f5edc1e8000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f5edc1b5000)
	libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007f5edbd89000)
	libGraphicsMagick.so.3 => /usr/lib/libGraphicsMagick.so.3 (0x00007f5edbbbe000)
	libSM.so.6 => /usr/lib/libSM.so.6 (0x00007f5edc1a8000)
	libICE.so.6 => /usr/lib/libICE.so.6 (0x00007f5edc18a000)
	libltdl.so.7 => /usr/lib/libltdl.so.7 (0x00007f5edc17f000)
	libdouble-conversion.so.3 => /usr/lib/libdouble-conversion.so.3 (0x00007f5edc169000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f5edc164000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f5edc15a000)
	libdatrie.so.1 => /usr/lib/libdatrie.so.1 (0x00007f5edc151000)
	libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x00007f5edbb9b000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f5edbb45000)
	libunistring.so.5 => /usr/lib/libunistring.so.5 (0x00007f5edb98b000)
	libidn2.so.0 => /usr/lib/libidn2.so.0 (0x00007f5edb969000)
	libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0x00007f5edb891000)
	libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0x00007f5edb863000)
	libcom_err.so.2 => /usr/lib/libcom_err.so.2 (0x00007f5edc149000)
	libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x00007f5edb855000)
	libkeyutils.so.1 => /usr/lib/libkeyutils.so.1 (0x00007f5edb84e000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f5edb83d000)
	libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007f5edb801000)
	libnghttp2.so.14 => /usr/lib/libnghttp2.so.14 (0x00007f5edb7d6000)
	libssh2.so.1 => /usr/lib/libssh2.so.1 (0x00007f5edb78d000)
	libssl.so.3 => /usr/lib/libssl.so.3 (0x00007f5edb6ed000)
	libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007f5edb000000)
	libzstd.so.1 => /usr/lib/libzstd.so.1 (0x00007f5edb618000)
	libgpgme.so.11 => /usr/lib/libgpgme.so.11 (0x00007f5edb5c2000)
	libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f5edb59c000)
	libassuan.so.0 => /usr/lib/libassuan.so.0 (0x00007f5edb587000)
	libnssutil3.so => /usr/lib/libnssutil3.so (0x00007f5edb555000)
	libplds4.so => /usr/lib/libplds4.so (0x00007f5edb54e000)
	libatspi.so.0 => /usr/lib/libatspi.so.0 (0x00007f5edb514000)
	libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007f5edafaf000)
	libjson-glib-1.0.so.0 => /usr/lib/libjson-glib-1.0.so.0 (0x00007f5edaf84000)
	libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007f5edb509000)
	libgfortran.so.5 => /usr/lib/libgfortran.so.5 (0x00007f5edac00000)
	libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f5edab18000)
	libcap.so.2 => /usr/lib/libcap.so.2 (0x00007f5edb4fd000)
	libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f5eda9d0000)
	liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f5edaf60000)
```

**Comment by burghoff** [comment]
It looks like you're still running the version of Scale Plots from the Inkscape website, as line 283 of scale_plots.py is now different. If you used the installer to add it, I think probably you need to uninstall it first? Then try adding the new version.

**Comment by gersonjferreira** [comment]
Yes! You are right! I'm sorry. I've download both from inkscape and from github, but I forgot to update.

**Comment by burghoff** [comment]
It's on the Inkscape site now.
