### ISSUE TITLE
Compatibility with inkscape 1.4?

### ISSUE THREAD

**Issue by jan-glx** [burghoff/Scientific-Inkscape#26]
When I try to use Scientific-Incskape v1.3.2 (current master, 3acb600)'s Autoexporter (pdf/png) with today's Inkscape 1.4-beta2, I get the following error after clicking "Apply":
```
Traceback (most recent call last):
  File "C:\Users\jan\AppData\Roaming\inkscape\extensions\scientific_inkscape\autoexporter.py", line 34, in <module>
    import dhelpers as dh
  File "C:\Users\jan\AppData\Roaming\inkscape\extensions\scientific_inkscape\dhelpers.py", line 32, in <module>
    import Style0
  File "C:\Users\jan\AppData\Roaming\inkscape\extensions\scientific_inkscape\Style0.py", line 44, in <module>
    class Style0(inkex.OrderedDict):
                 ^^^^^^^^^^^^^^^^^
AttributeError: module 'inkex' has no attribute 'OrderedDict'
```
(after replacing all instances with collections.OrderedDict other issues arise. Is Scientific-Inkscape supporting 1.4 ?

```
Inkscape 1.4-beta2 (117f060, 2024-08-27, custom)

                    Compile  (Run)
  GLib version:     2.80.3
  GTK version:      3.24.42 (3.24.42)
  glibmm version:   2.66.7
  gtkmm version:    3.24.9
  libxml2 version:  2.12.8
  libxslt version:  1.1.42
  Cairo version:    1.18.0 (1.18.0)
  Pango version:    1.54.0 (1.54.0)
  HarfBuzz version: 9.0.0 (9.0.0)

  OS version:       Windows 11 23H2
  ```

**Comment by jan-glx** [comment]
Oh. just saw there is a dev branch 😬

**Comment by jan-glx** [comment]
... which works like a charm! Sorry for the noise.

**Comment by burghoff** [comment]
No problem! Actually, thanks for the reminder that I should do an official release for v1.4.
