### ISSUE TITLE
bug in autoexporter

### ISSUE THREAD

**Issue by wandida** [burghoff/Scientific-Inkscape#6]
hey,

I get the following error by exporting some svgs with the autoexporter:

```
Traceback (most recent call last):
  File "C:\Users\David\AppData\Roaming\inkscape\extensions\Scientific-Inkscape-main\scientific_inkscape\autoexporter.py", line 1270, in <module>
    dh.Run_SI_Extension(AutoExporter(),"Autoexporter")
  File "C:\Users\David\AppData\Roaming\inkscape\extensions\Scientific-Inkscape-main\scientific_inkscape\dhelpers.py", line 2115, in Run_SI_Extension
    effext.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 231, in run
    self.save_raw(self.effect())
  File "C:\Users\David\AppData\Roaming\inkscape\extensions\Scientific-Inkscape-main\scientific_inkscape\autoexporter.py", line 295, in effect
    AutoExporter().export_all(
  File "C:\Users\David\AppData\Roaming\inkscape\extensions\Scientific-Inkscape-main\scientific_inkscape\autoexporter.py", line 349, in export_all
    self.Add_Margin(svg,input_options.margin)
  File "C:\Users\David\AppData\Roaming\inkscape\extensions\Scientific-Inkscape-main\scientific_inkscape\autoexporter.py", line 1155, in Add_Margin
    nvb = [vb[0]-m/uuw,vb[1]-m/uuh,vb[2]+2*m/uuw,vb[3]+2*m/uuh]
ZeroDivisionError: float division by zero
```

+ It happes with svgs exported in matlab by: https://de.mathworks.com/matlabcentral/fileexchange/71301-fig2svg
+ The manual Inkscape export works
+ The error appears in all export formats of the autoexporter

**Comment by wandida** [comment]
![test](https://user-images.githubusercontent.com/122943487/213907689-a32d0ad8-b33b-4373-a803-992347d0b0a0.svg)

This grafic e.g. creates the error

**Comment by burghoff** [comment]
Thanks for the bug. The issue is with documents whose sizes are specified in percentages rather than an absolute unit, which Inkscape doesn't usually generate.

I'll do a fix soon, but in the meantime a workaround is to change the page width (in Document Properties) to anything. Inkscape will automatically replace the percentages, and the Autoexporter will work.

**Comment by burghoff** [comment]
It's fixed. If you want to use it, download the new version of [dhelpers.py](https://github.com/burghoff/Scientific-Inkscape/blob/main/scientific_inkscape/dhelpers.py) and [autoexporter.py](https://github.com/burghoff/Scientific-Inkscape/blob/main/scientific_inkscape/autoexporter.py).
